### PR TITLE
Add monero connections manager

### PR DESCRIPTION
**Pull request by LumnitzF**
[haveno issue 138](https://github.com/haveno-dex/haveno/issues/138)

### CODE REVIEW

**Comment by woodser** [comment]
Please rebase to resolve conflicting files with current master.

**Comment by LumnitzF** [comment]
done

**Comment by woodser** [comment]
Nice, thanks.

**Comment by woodser** [comment]
Please rebase on latest master to resolve the merge conflicts. Sorry for the inconvenience.

**Pull request merged**
